# Generated by Django 4.0.3 on 2022-04-03 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_remove_asset_stock_asset_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price per stock'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='asset',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='transactions.stock'),
        ),
    ]
