# Generated by Django 4.0.3 on 2022-04-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_asset_price_alter_asset_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='price',
            field=models.FloatField(verbose_name='Price per stock'),
        ),
    ]
