# Generated by Django 4.0.3 on 2022-04-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_balance_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='sum',
            field=models.FloatField(default=0),
        ),
    ]
